version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: postcss
        versions:
          - 8.2.10
          - 8.2.12
      - dependency-name: gatsby-plugin-sharp
        versions:
          - 3.0.1
          - 3.1.0
          - 3.1.1
          - 3.1.2
          - 3.2.1
          - 3.3.0
          - 3.3.1
      - dependency-name: gatsby-remark-responsive-iframe
        versions:
          - 4.0.0
      - dependency-name: gatsby-source-filesystem
        versions:
          - 2.11.1
          - 3.3.0
      - dependency-name: gatsby-remark-copy-linked-files
        versions:
          - 2.10.0
          - 3.1.0
          - 4.0.0
      - dependency-name: gatsby-plugin-manifest
        versions:
          - 2.12.1
          - 3.3.0
      - dependency-name: eslint
        versions:
          - 7.22.0
          - 7.23.0
          - 7.24.0
      - dependency-name: "@typescript-eslint/parser"
        versions:
          - 4.18.0
          - 4.19.0
          - 4.20.0
          - 4.21.0
      - dependency-name: "@typescript-eslint/eslint-plugin"
        versions:
          - 4.15.2
          - 4.16.1
          - 4.18.0
          - 4.19.0
          - 4.20.0
          - 4.21.0
      - dependency-name: tailwindcss
        versions:
          - 2.1.1
      - dependency-name: react-dom
        versions:
          - 17.0.2
      - dependency-name: react
        versions:
          - 17.0.2
      - dependency-name: gatsby-remark-vscode
        versions:
          - 3.2.1
      - dependency-name: gatsby
        versions:
          - 2.32.6
          - 2.32.8
          - 3.1.0
          - 3.1.1
          - 3.1.2
          - 3.2.0
      - dependency-name: "@types/react-dom"
        versions:
          - 17.0.1
          - 17.0.3
      - dependency-name: gatsby-remark-images
        versions:
          - 3.11.1
          - 4.1.0
          - 4.1.1
      - dependency-name: gatsby-plugin-typescript
        versions:
          - 3.1.0
      - dependency-name: gatsby-transformer-sharp
        versions:
          - 2.12.0
          - 3.1.0
      - dependency-name: gatsby-plugin-google-analytics
        versions:
          - 3.1.0
      - dependency-name: gatsby-plugin-styled-components
        versions:
          - 4.1.0
      - dependency-name: "@types/node"
        versions:
          - 14.14.35
      - dependency-name: "@types/styled-components"
        versions:
          - 5.1.9
      - dependency-name: bulma
        versions:
          - 0.9.2
      - dependency-name: gatsby-plugin-feed
        versions:
          - 2.13.0
      - dependency-name: netlify-cms-app
        versions:
          - 2.14.25
