# This is a basic workflow to help you get started with Actions

on: pull_request_target
name: Build Gatsby Site
jobs:
  build:
    name: Build Gatsby Site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set Node.js
      uses: actions/setup-node@master
      with:
        node-version: 14.x
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --pure-lockfile

    - name: Build
      run: yarn run build

  automerge:
    needs: build
    # if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: echo "MY_GH_TOKEN ${{ secrets.MY_GH_TOKEN }}"

    - uses: ahmadnassri/action-dependabot-auto-merge@v2
      with:
        target: minor
        github-token: ${{ secrets.MY_GH_TOKEN }}
    
    # - uses: fastify/github-action-merge-dependabot@v2.0.0
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}

