name: Build Gatsby Site

on:
  pull_request:
  # You can be more specific and filter by dependabot branch name
  # branches:
  #   - 'dependabot/**'

jobs:
  build:
    name: Build Gatsby Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Tests
        run: yarn run test:ci

      - name: Build
        run: yarn run build

  automerge:
    needs: build
    # run this step only for dependabot
    # "github.head_ref" is only available for pull requests
    if: contains(github.head_ref, 'dependabot')
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.MY_GH_TOKEN }}
