name: "[cron] merge dev -> master"

on:
  schedule:
    - cron: "0 8 * * 6" # “At 08:00 on Saturday.”
  workflow_dispatch:

jobs:
  nightly-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Merge dev -> master
        uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          from_branch: dev
          target_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
